name: Update lock file 

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format:
    name: Format tf files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Set terraform version
      run: echo "VERSION=$(cat .terraform-version)" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.VERSION }}
    
    - name: Deploy and Commit
      run: |
        cd ${GITHUB_WORKSPACE}
        echo 'Check terraform fmt'
        if
          ! terraform fmt -recursive -check
        then
          echo 'Run terraform fmt'
          terraform fmt -recursive
          echo 'Configure git'
          git config user.name "Sample Action"
          git config user.email "sample@example.com"
          git remote set-url origin "https://${{github.repository_owner}}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          echo 'Create commit and push'
          git add .
          git commit -m "Format tf files"
          git push origin ${{github.head_ref}}
        fi
