name: Update lock file 

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format:
    name: Format tf files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Set terraform version
      run: echo "VERSION=$(cat .terraform-version)" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.VERSION }}
    
    - name: Deploy and Commit
      run: |
        cd ${GITHUB_WORKSPACE}
        echo 'Run terraform fmt'
        ws_dirs=($(find . -type f -name '*.tf' | xargs -L1 dirname | uniq))
        for workspace in "${ws_dirs[@]}"; do
          echo "Execute on $workspace"
          pushd $workspace
          terraform fmt
          popd
        done
        if
          ! git diff --exit-code --quiet -- **/*.tf &&
          git diff --exit-code --quiet -- ':(exclude)**/*.tf'
        then
          # Commit all changes when if terraform fmt command makes diff
          # Configure git
          echo 'git initialize'
          git config user.name "Test Actions"
          git config user.email "sample@example.com"
          git remote set-url origin "https://${{github.repository_owner}}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          # Create commit and push
          git add .
          git commit -m "Format tf files"
          git push origin ${{github.head_ref}}
        fi
