name: Terraform init

on:
  pull_request:
    paths:
    - '**/versions.tf'

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'renovate/') || startsWith(github.head_ref, 'shimada/') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Set terraform version
      run: echo "VERSION=$(cat .terraform-version)" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.VERSION }}
    
    - name: Deploy and Commit
      run: |
        cd ${GITHUB_WORKSPACE}
        echo 'Run terraform init'
        ws_dirs=($(git diff ${{github.head_ref}} ${{github.base_ref}} --name-only | xargs -L1 dirname | uniq))
        echo $ws_dirs
        for workspace in "${ws_dirs[@]}"; do
          echo "Execute on $workspace"
          pushd $workspace
          terraform init -upgrade -backend=false
          popd
        done
        if 
          ! git diff --exit-code --quiet -- tenants/*/.terraform.lock.hcl &&
          git diff --exit-code --quiet -- ':(exclude)tenants/*/.terraform.lock.hcl'
        then
          # .terraform.lock.hcl ファイルのみに差分がある場合はコミット
          echo 'git initialize'
          git config --global user.name "GitHub Actions"
          git config --global user.email "example@example.com"
          git remote set-url origin "https://${{github.repository_owner}}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git add .
          git commit -m "Update lock file";\
          git push origin ${{github.head_ref}}
        elif 
          ! git diff --exit-code --quiet -- ':(exclude)tenants/*/.terraform.lock.hcl'
        then
          echo 'diff detected'
          git diff
          exit 1
        else
          echo "no diff"
        fi