name: Terraform init

on:
  pull_request:
    paths:
    - '**/versions.tf'

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'renovate/') || startsWith(github.head_ref, 'shimada/') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Set terraform version
      run: |
        VER=$(cat .terraform-version)
        echo "VERSION=$VER" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.VERSION }}
    
    - name: Deploy and Commit
      run: |
        cd ${GITHUB_WORKSPACE}
        # git設定
        echo 'git initialize'
        git config --global user.name "GitHub Actions"
        git config --global user.email "example@example.com"
        git remote set-url origin "https://${{github.repository_owner}}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        echo 'Run terraform init'
        array=($(find . -type d -mindepth 1 -maxdepth 1 ! -regex "\.*\/\..*"))
        for directory in "${array[@]}"; do
          echo "Execute on $directory"
          cd $directory
          terraform init -upgrade 
          cd ../
        done
        # コミットを作成する
        echo 'create commit'
        git add .
        # This script will not make a commit if there are no changes.
        if ! git diff --staged --exit-code --quiet; then \
          git commit -m "Update lock file";\
        fi
        git push origin ${{github.head_ref}}